apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql
data:
  AUTH_SERVER_HOST: ""
  DB_HOST: ""
  AUTH_SERVER_PORT: "8099"
  SERVER_PORT: "8080"
  DB_USERNAME: "myuser"
  DB_PASSWORD: "secret"
  DB_PORT: "5432"
  DB_NAME: "graphql_course"
  SPRING_PROFILES_ACTIVE: "docker"
  ACTUATOR_EXPOSED_ENDPOINT: "health"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: graphql
  name: graphql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - image: zikozee/gjar:1.0
          name: graphql
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 800m
              memory: 3Gi
            requests:
              cpu: 400m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: graphql
          imagePullPolicy: IfNotPresent
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: graphql
  name: graphql-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32000
  type: NodePort
  selector:
    app: graphql